name: Tauri Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [web, macos, windows, linux, android, ios]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build PWA (Web Platform)
        if: matrix.platform == 'web'
        run: |
          pnpm run build
        timeout-minutes: 10

      - name: Build Tauri App (Desktop Platforms)
        run: |
          if [ "${{ matrix.platform }}" == "macos" ]; then
            pnpm tauri build --target dmg
          elif [ "${{ matrix.platform }}" == "windows" ]; then
            pnpm tauri build --target msix
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            pnpm tauri build --target app-image
          elif [ "${{ matrix.platform }}" == "android" ]; then
            pnpm tauri build --target android
          elif [ "${{ matrix.platform }}" == "ios" ]; then
            pnpm tauri build --target ios
          fi
        timeout-minutes: 30

      - name: Install GitHub CLI
        run: |
          curl -s https://cli.github.com/install.sh | bash

      - name: Create Release with GitHub CLI
        run: |
          VERSION="v$(date +'%Y%m%d%H%M%S')"
          gh release create $VERSION ./dist/* --title "Automated Release $VERSION" --notes "Automated build of version $VERSION"

